export const LIST_SET_COINS = 'LIST_SET_COINS'
export const LIST_APPLY_SORTING = 'LIST_APPLY_SORTING'
export const LIST_SET_LOADING = 'LIST_SET_LOADING'
export const LIST_SET_ERROR = 'LIST_SET_ERROR'

export const COIN_SET_BASIC_INFO = 'COIN_SET_BASIC_INFO'
export const COIN_SET_MARKET_INFO = 'COIN_SET_MARKET_INFO'
export const COIN_SET_LOADING = 'COIN_SET_LOADING'
export const COIN_SET_ERROR = 'COIN_SET_ERROR'

