export const LIST_SET_COINS = 'LIST_SET_COINS'
export const LIST_APPLY_SORTING = 'LIST_APPLY_SORTING'
export const LIST_SET_LOADING = 'LIST_SET_LOADING'
export const LIST_SET_ERROR = 'LIST_SET_ERROR'
